In [ ]:

import tensorflow as tf

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical



# Load the dataset
data = pd.read_csv('/content/Driving Behavior Dataset.csv')

#Display the first five rows
data.head()

AccX      AccY      AccZ     GyroX     GyroY     GyroZ  \
0  0.758194 -0.217791  0.457263  0.000000  0.000000  0.000000   
1  0.667560 -0.038610  0.231416 -0.054367 -0.007712  0.225257   
2  2.724449 -7.584121  2.390926  0.023824  0.013668 -0.038026   
3  2.330950 -7.621754  2.529024  0.056810 -0.180587 -0.052076   
4  2.847215 -6.755621  2.224640 -0.031765 -0.035201  0.035277   

  Class(class attribute)  
0             AGGRESSIVE  
1             AGGRESSIVE  
2             AGGRESSIVE  
3             AGGRESSIVE  
4             AGGRESSIVE

In [ ]:
#Check missing values
print("\n Missing values\n\n", data.isnull().sum())




 Missing values

 AccX     0
AccY     0
AccZ     0
GyroX    0
GyroY    0
GyroZ    0
Class    0
dtype: int64


In [ ]:
# Encode target labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_categorical = to_categorical(y_encoded)
print(y_encoded)
print(y_categorical)

[1 1 1 ... 3 3 3]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [ ]:
# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)


[[ 0.67356021 -0.09510542  0.41330115 -0.04791257 -0.01200489 -0.10106389]
 [ 0.57992349  0.10304771  0.18687905 -0.86392455 -0.07577152  1.88329278]
 [ 2.70495908 -8.24143985  2.35188139  0.30966571  0.10100724 -0.43605021]
 ...
 [ 1.21287745 -1.7731585  -2.38375226  8.70817103  5.69731749 -4.22448964]
 [ 0.83278503  0.79082629 -1.01320251  3.49119555  4.22752831  3.47615948]
 [ 1.40086138  0.35618221 -0.0256992  -3.87124984 -2.32338703  0.57025406]]


In [ ]:
# Split the dataset into training (80%) and testing (20%) sets

X_train, X_test, y_train, y_test = train_test_split(X_scaled,
y_categorical, test_size=0.2, random_state=42)


In [ ]:
# Build the neural network
model = Sequential([
    Dense(64, input_shape=(6,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(y_categorical.shape[1], activation='softmax')
])
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 4)              │           132 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,660 (10.39 KB)

 Trainable params: 2,660 (10.39 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

Epoch 1/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.3721 - loss: 1.2997 - val_accuracy: 0.3846 - val_loss: 1.1245
Epoch 2/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4247 - loss: 1.1104 - val_accuracy: 0.4130 - val_loss: 1.0773
Epoch 3/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4493 - loss: 1.0639 - val_accuracy: 0.4372 - val_loss: 1.0615
Epoch 4/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4776 - loss: 1.0388 - val_accuracy: 0.4332 - val_loss: 1.0570
Epoch 5/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4710 - loss: 1.0491 - val_accuracy: 0.4251 - val_loss: 1.0506
Epoch 6/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4929 - loss: 1.0153 - val_accuracy: 0.4008 - val_loss: 1.0516
Epoch 7/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5006 - loss: 1.0080 - val_accuracy: 0.4453 - val_loss: 1.0432
Epoch 8/50
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5050 - loss: 0.9987 - val_accuracy: 0.4332 - val_loss:

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nTest Accuracy: {accuracy:.2f}")

KeyError: "['behavior'] not found in axis"